pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - ./spin_up_test_environment.sh
          after-script:
            - ./cleanup.sh
      - step:
          name: Release
          deployment: production
          script:
            - ./release.sh
          after-script:
            - ./send_notifcation.sh $BITBUCKET_EXIT_CODE